service: message-batch-profiling

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stackName: ${self:service}
  tracing:
    lambda: true

package:
  exclude:
    - .github/**
    - resources/**
    - requirements.txt
    - README.md

functions:

  BatchProfilerIndividual:
    handler: src.batch_profiler_individual.entry_point
    name: BatchProfilerIndividual
    description: A lambda function to send messages individually
    environment:
      LOG_LEVEL: DEBUG
      TARGET_QUEUE_NAME: ${self:provider.stackName}-TargetQueue
      TARGET_STREAM_NAME: ${self:provider.stackName}-TargetKinesisStream
    memorySize: 128
    iamRoleStatementsName: ${self:provider.stackName}-BatchProfilerIndividual
    iamRoleStatements:
      - Effect: Allow
        Sid: xray
        Action:
          - "xray:*"
        Resource:
          - "*"
      - Effect: Allow
        Sid: "TargetQueue"
        Action:
          - SQS:SendMessage
          - SQS:GetQueueAttributes
          - SQS:GetQueueUrl
          - SQS:ListQueueTags
          - SQS:ChangeMessageVisibility
        Resource:
          - { "Fn::GetAtt": ["TargetQueue", "Arn"] }
      - Effect: Allow
        Sid: "TargetStream"
        Action:
          - kinesis:PutRecord
        Resource:
          - { "Fn::GetAtt": ["TargetKinesisStream", "Arn"] }

  BatchProfilerBatch:
    handler: src.batch_profiler_batch.entry_point
    name: BatchProfilerBatch
    description: A lambda function to send messages in batches
    environment:
      LOG_LEVEL: DEBUG
      TARGET_QUEUE_NAME: ${self:provider.stackName}-TargetQueue
      TARGET_STREAM_NAME: ${self:provider.stackName}-TargetKinesisStream
    memorySize: 128
    iamRoleStatementsName: ${self:provider.stackName}-BatchProfilerBatch
    iamRoleStatements:
      - Effect: Allow
        Sid: xray
        Action:
          - "xray:*"
        Resource:
          - "*"
      - Effect: Allow
        Sid: "TargetQueue"
        Action:
          - SQS:SendMessage
          - SQS:GetQueueAttributes
          - SQS:GetQueueUrl
          - SQS:ListQueueTags
          - SQS:ChangeMessageVisibility
        Resource:
          - { "Fn::GetAtt": ["TargetQueue", "Arn"] }
      - Effect: Allow
        Sid: "TargetStream"
        Action:
          - kinesis:PutRecords
        Resource:
          - { "Fn::GetAtt": ["TargetKinesisStream", "Arn"] }

  BatchProfilerBoto3BatchUtils:
    handler: src.batch_profiler_boto3_batch_utils.entry_point
    name: BatchProfilerBoto3BatchUtils
    description: A lambda function to send messages using boto3-batch-utils
    environment:
      LOG_LEVEL: DEBUG
      TARGET_QUEUE_NAME: ${self:provider.stackName}-TargetQueue
      TARGET_STREAM_NAME: ${self:provider.stackName}-TargetKinesisStream
    memorySize: 128
    iamRoleStatementsName: ${self:provider.stackName}-BatchProfilerBoto3BatchUtils
    iamRoleStatements:
      - Effect: Allow
        Sid: xray
        Action:
          - "xray:*"
        Resource:
          - "*"
      - Effect: Allow
        Sid: "TargetQueue"
        Action:
          - SQS:SendMessage
          - SQS:GetQueueAttributes
          - SQS:GetQueueUrl
          - SQS:ListQueueTags
          - SQS:ChangeMessageVisibility
        Resource:
          - { "Fn::GetAtt": ["TargetQueue", "Arn"] }
      - Effect: Allow
        Sid: "TargetStream"
        Action:
          - kinesis:PutRecord
          - kinesis:PutRecords
        Resource:
          - { "Fn::GetAtt": ["TargetKinesisStream", "Arn"] }

resources:
  Resources:
    TargetQueue:
      Type: AWS::SQS::Queue
      Properties:
        VisibilityTimeout: 30
        DelaySeconds: 0
        MaximumMessageSize: 262144
        MessageRetentionPeriod: 7200
        QueueName: ${self:provider.stackName}-TargetQueue

    TargetKinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.stackName}-TargetKinesisStream
        RetentionPeriodHours: 24
        ShardCount: 1