name: Master Pipeline
on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@master
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Deployment Tools
      run: |
        sudo apt-get install python3-setuptools
        npm install -g serverless
        npm install
    - name: Deploy
      run:
        sls deploy --region eu-west-1 --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

